language: java
sudo: false
script:
        - cd MinVakt
        - mvn test
jdk:
  - oraclejdk8
branches:
   only:
      - master
      - development
notifications:
  slack: dat15hscrum1:STbUzEN3OEb7Kd8SfUGahsDd
  email: false
