language: java
sudo: false
script: cd MinVakt && mvn clean verify
jdk:
  - oraclejdk8
branches:
   only:
      - master
      - development
notifications:
  slack: dat15hscrum1:STbUzEN3OEb7Kd8SfUGahsDd
  email: false
